import './js/buy-now';
import './js/modal-review';
import './js/mobile-menu';
import './js/modal-subscribe';
import './js/modal-thanks';
import './js/modal-feedback';
// import './js/how-its-made.js';
import './js/slick.min';
import './js/modal-buy-now';
import './js/swiper';
