import './js/buy-now';
import './js/modal-review';
import './js/mobile-menu';
// import './js/how-its-made.js';
import './js/modal-subscribe';
import './js/modal-thanks';
import './js/modal-feedback';
import './js/swiper.js';
import './js/slick.min.js';
import './js/modal-buy-now.js';
